"""Generate the Python/C# cross-validation fixture.

The Eddy3D C# port re-implements the admittance solver from scratch (MathNet FFT instead of
numpy, hand-rolled complex arithmetic instead of numpy's). Nothing else forces the two to agree
numerically, and a port error is silent: the C# result stays smooth and plausible while being
wrong.

This writes a fixture of solved cases that BOTH sides assert against. Python regenerates and
compares (so the fixture cannot go stale unnoticed); C# reads the same file and must reproduce
the same surface temperatures.

Run: ``uv run python scripts/generate_crossvalidation.py``
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path

import numpy as np

from surface_temps.admittance import solve_surface_temperature
from surface_temps.materials import (
    Assembly,
    Layer,
    brick_ground,
    brick_wall,
    concrete_ground,
    concrete_roof,
    grass_ground,
)

OUT = Path(__file__).resolve().parents[1] / "data" / "crossvalidation" / "admittance_cases.json"

# Deliberately short series: enough harmonics to exercise the transfer function, small enough
# that the fixture stays readable and diffable.
N_HOURS = 168  # one week


def _driving(kind: str, n: int) -> np.ndarray:
    t = np.arange(n, dtype=float)
    if kind == "sinusoid_daily":
        return 20.0 + 12.0 * np.sin(2.0 * np.pi * t / 24.0)
    if kind == "sinusoid_daily_plus_weekly":
        return (
            18.0
            + 10.0 * np.sin(2.0 * np.pi * t / 24.0)
            + 4.0 * np.sin(2.0 * np.pi * t / 168.0 + 0.7)
        )
    if kind == "sawtooth_daily":
        u = t % 24.0
        return 15.0 + 8.0 * (2.0 * np.abs(2.0 * (u / 24.0) - 1.0) - 1.0)
    if kind == "step_train":
        return np.where((t % 24.0) < 12.0, 28.0, 8.0)
    if kind == "constant":
        return np.full(n, 25.0)
    raise ValueError(kind)


def _assembly_spec(assembly: Assembly) -> dict:
    return {
        "R_si": assembly.R_si,
        "R_so": assembly.R_so,
        "layers": [
            {
                "thickness": layer.thickness,
                "conductivity": layer.conductivity,
                "density": layer.density,
                "specific_heat": layer.specific_heat,
            }
            for layer in assembly.layers
        ],
    }


def build_cases() -> list[dict]:
    single = Assembly(
        layers=[Layer(thickness=0.20, conductivity=1.40, density=2100, specific_heat=840)],
        R_si=0.13,
        R_so=0.04,
    )
    bare = Assembly(layers=[], R_si=0.13, R_so=0.04)

    specs = [
        ("single_concrete_sinusoid", single, "sinusoid_daily", 20.0),
        ("single_concrete_sawtooth", single, "sawtooth_daily", 20.0),
        ("single_concrete_steps", single, "step_train", 20.0),
        ("bare_resistance_divider", bare, "sinusoid_daily", 20.0),
        ("bare_constant_steady_state", bare, "constant", 10.0),
        ("brick_wall_two_scales", brick_wall(), "sinusoid_daily_plus_weekly", 22.0),
        ("concrete_roof_sinusoid", concrete_roof(), "sinusoid_daily", 22.0),
        ("concrete_ground_sawtooth", concrete_ground(), "sawtooth_daily", 16.0),
        ("brick_ground_sinusoid", brick_ground(), "sinusoid_daily", 16.0),
        ("grass_ground_steps", grass_ground(), "step_train", 16.0),
    ]

    cases = []
    for name, assembly, driving_kind, t_internal in specs:
        T_driving = _driving(driving_kind, N_HOURS)
        T_surface = solve_surface_temperature(T_driving, assembly, T_internal=t_internal)
        cases.append(
            {
                "name": name,
                "driving_kind": driving_kind,
                "T_internal": t_internal,
                "assembly": _assembly_spec(assembly),
                "T_driving": [round(float(v), 10) for v in T_driving],
                "T_surface_expected": [round(float(v), 10) for v in T_surface],
            }
        )
    return cases


def main() -> None:
    cases = build_cases()
    payload = {
        "schema_version": 1,
        "description": (
            "Cross-validation fixture for the frequency-domain admittance solver. Generated by "
            "scripts/generate_crossvalidation.py in the SurfaceTemps repository, which is the "
            "canonical source. The Eddy3D C# port embeds a byte-identical copy and asserts the "
            "same expected values; if you regenerate this file you MUST copy it into "
            "Eddy3D/Radiance.Core/Resources/ or the two implementations will silently diverge."
        ),
        "n_hours": N_HOURS,
        "dt_seconds": 3600.0,
        "cases": cases,
    }
    body = json.dumps(payload, indent=2, sort_keys=True)
    digest = hashlib.sha256(body.encode()).hexdigest()
    payload["content_sha256"] = digest

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n")
    print(f"wrote {OUT} ({len(cases)} cases, sha256 of body {digest[:16]}...)")


if __name__ == "__main__":
    main()
